name: Deploy to Cloud Run

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

  
    - name: Request OIDC token
      id: oidc
      run: |
        echo "Requesting ID token..."
        curl -sLS -o token.json "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=google-cloud" \
          -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        cat token.json | jq -r '.value' | awk -F. '{print $2}' | base64 -d | jq .
      env:
        ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACTIONS_ID_TOKEN_REQUEST_URL: ${{ steps.auth.outputs.id_token_url || '' }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: 'id_token'
        workload_identity_provider: 'projects/780061552535/locations/global/workloadIdentityPools/github-actions/providers/github'
        service_account: 'github-actions-sa@gcdeveloper-new.iam.gserviceaccount.com'

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        IMAGE="asia-south1-docker.pkg.dev/gcdeveloper-new/salesforce-mcp/server"
        docker build -t "$IMAGE:$GITHUB_SHA" .
        docker push "$IMAGE:$GITHUB_SHA"

