on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - uses: aws-actions/setup-sam@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names mcp-salesforce-server || \
          aws ecr create-repository --repository-name mcp-salesforce-server
        
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t mcp-salesforce-server:latest .

      - name: Tag Docker Image
        run: |
          docker tag mcp-salesforce-server:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/mcp-salesforce-server:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/mcp-salesforce-server:latest

      - name: SAM Build
        run: sam build --template-file service.yaml --use-container

      - name: SAM Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM
      
      - name: Force ECS Service Redeployment
        run: aws ecs update-service --cluster mcp-ecs-cluster --service mcp-salesforce-ecs-ECSService-7nzRgWn0QhSb --force-new-deployment

